### ISSUE TITLE
您的开源项目有问题，而且还没有找到数据库的链接方式

### ISSUE THREAD

**Issue by 1101916341** [Shekcon/Nestjs-API#1]

**Comment by shekcon** [comment]
Can u give me more information about that ?

**Comment by 1101916341** [comment]
> 你可以给我更多相关信息吗？

您的项目在build的时候，有一个.ts文件在判断时，有一个 number类型的 id  和 string类型id做判断，nest自动判断出是不对等关系，而且我没有看到您项目中的数据库连接的配置文件和配置信息

**Comment by shekcon** [comment]
Please attach that file into comment so I can understand what problem is ? Or example code about What u want ?

**Comment by 1101916341** [comment]
> 请将该文件附加到评论中，以便了解问题是什么？或者关于你想要什么的示例代码？

/src/modules/auth/guards/claim.guard.ts 这个路径下


canActivate(context: ExecutionContext): boolean {
  const hasClaim = (claim: any, req: IRequest): boolean =>
    **req.params.id == req.user.id;**  // 这里的判断有问题，执行在这里就会出错
  return validate(AuthType.Claim, hasClaim, this.reflector, context);
}

**Comment by 1101916341** [comment]
> 请将该文件附加到评论中，以便了解问题是什么？或者关于你想要什么的示例代码？

您那边方便做一个线上的demo 出来吗？就是连接能访问的

**Comment by shekcon** [comment]
Did u test online here ?
https://nestjs-api-shekcon.herokuapp.com/api/

**Comment by 1101916341** [comment]
> Did u test online here ?
> https://nestjs-api-shekcon.herokuapp.com/api/

您好，这里确实没有体验过，但是关于代码运行报错的问题您看下是什么情况啊

**Comment by 1101916341** [comment]
> > Did u test online here ?
> > https://nestjs-api-shekcon.herokuapp.com/api/
> 
> 您好，这里确实没有体验过，但是关于代码运行报错的问题您看下是什么情况啊

您用的数据库是mysql  还是mongoDB啊

**Comment by shekcon** [comment]
My app use PostgreSQL on heroku

**Comment by shekcon** [comment]
Can u show screenshot about your error ?

**Comment by shekcon** [comment]
If you use mongoDB then you need redesign whole code about entity because TypeORM works with mongodb quite different with SQL. U can read docs on typeorm website. [typeorm with mongodb](https://typeorm.io/#/mongodb)
